
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 13 09:44:04 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 28;
  public static final int CONST = 26;
  public static final int GE = 35;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int FOR = 42;
  public static final int MINUS = 23;
  public static final int RPAREN = 7;
  public static final int AND = 39;
  public static final int LT = 36;
  public static final int OR = 38;
  public static final int COMMA = 11;
  public static final int DIV = 25;
  public static final int PLUS = 10;
  public static final int IF = 19;
  public static final int DOT = 15;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 29;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int TRUE = 40;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int NUMBER = 16;
  public static final int MOD = 31;
  public static final int NEQ = 33;
  public static final int BREAK = 43;
  public static final int IDENT = 17;
  public static final int VOID = 14;
  public static final int EQ = 32;
  public static final int LBRACK = 21;
  public static final int LBRACE = 3;
  public static final int ELSE = 20;
  public static final int ENUM = 30;
  public static final int READ = 13;
  public static final int RBRACK = 22;
  public static final int CHARCONST = 18;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int FALSE = 41;
  public static final int GT = 34;
  public static final int PRINT = 12;
}

